name: outline CI

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Miniconda
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
        bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
        echo "::add-path::$HOME/miniconda/bin"
    - name: Install tectonic
      run: conda install -y -c conda-forge tectonic
    - name: Typeset outline
      run: tectonic outline.tex
    - name: Archive outline.pdf
      uses: actions/upload-artifact@v1
      with:
        name: outline.pdf
        path: outline.pdf   
            
